# Generated by Django 5.2.3 on 2025-06-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dds_app', '0002_alter_transaction_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
