# Generated by Django 5.2.3 on 2025-06-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_app', '0003_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Подкатегория'),
        ),
    ]
