# Generated by Django 5.2.3 on 2025-06-15 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds_app', '0004_alter_category_name_alter_operationtype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dds_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dds_app.operationtype', verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dds_app.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dds_app.subcategory', verbose_name='Подкатегория'),
        ),
    ]
